### ISSUE TITLE
the problem of the syntax highlight

### ISSUE THREAD

**Issue by Nitcloud** [go2sh/tcl-language-support#1]
![screenShot.png](https://i.loli.net/2020/03/20/a6ltUh3A8kgo5bN.png)
when the "{" is at the same line of the "while" or "if",there is no syntax highlight
when the "{" is at the next line, it works.
![screenShot.png](https://i.loli.net/2020/03/20/PafgbtDOxSuMFsc.png)
however,when i set  the "{"  at the next line,Syntax errors are reported at runtime.
how can i solve it?

**Comment by go2sh** [comment]
I'll check that. `while` might be missing.

**Comment by go2sh** [comment]
I released a new verion. 🎆
