### ISSUE TITLE
Support 'foreach' syntax highlighting

### ISSUE THREAD

**Issue by Nabav** [go2sh/tcl-language-support#2]
The `foreach` [command](https://www.tcl.tk/man/tcl8.6/TclCmd/foreach.htm) is not defined in syntax definition file. Therefore, the `for` part is highlighted and the remaining `each` part is left unattended.

**Comment by go2sh** [comment]
Yeah, I know. I will add that. There are some more `for` stuff that is missing. (e.g. dict) I think, I have time tomorrow.

**Comment by go2sh** [comment]
I released a new version with some more syntax highlighting
