### ISSUE TITLE
Maintainer needed?

### ISSUE THREAD

**Issue by ubfx** [go2sh/tcl-language-support#5]
Hey,

I think this is the best TCL extension in the VSCode Marketplace, but there are some kind of annoying bugs. Are you still actively maintaining the project? If you make me a maintainer, I'll happily fix the most annoying small bugs.

**Comment by go2sh** [comment]
Hi, 
I'am still maintaining it, but I developed every thing I needed. If you want to report/fix bugs, I'll be happy to help you. Please feel free to submit prs and bug reports.
